

# This file was *autogenerated* from the file 12/12.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_0p25 = RealNumber('0.25'); _sage_const_1024 = Integer(1024); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4)# Boneh-Duffee Attack

from Crypto.Util.number import *
from sage.all import *
import itertools

with open("12/output.txt", "r") as f:
    n = Integer(int(f.readline().split(" = ")[_sage_const_1 ]))
    e = Integer(int(f.readline().split(" = ")[_sage_const_1 ]))
    c = Integer(int(f.readline().split(" = ")[_sage_const_1 ]))

#From https://github.com/defund/coppersmith/blob/master/coppersmith.sage
def small_roots(f, bounds, m=_sage_const_1 , d=None):
	if not d:
		d = f.degree()

	R = f.base_ring()
	N = R.cardinality()
	
	f /= f.coefficients().pop(_sage_const_0 )
	f = f.change_ring(ZZ)

	G = Sequence([], f.parent())
	for i in range(m+_sage_const_1 ):
		base = N**(m-i) * f**i
		for shifts in itertools.product(range(d), repeat=f.nvariables()):
			g = base * prod(map(power, f.variables(), shifts))
			G.append(g)

	B, monomials = G.coefficient_matrix()
	monomials = vector(monomials)

	factors = [monomial(*bounds) for monomial in monomials]
	for i, factor in enumerate(factors):
		B.rescale_col(i, factor)

	B = B.dense_matrix().LLL()

	B = B.change_ring(QQ)
	for i, factor in enumerate(factors):
		B.rescale_col(i, _sage_const_1 /factor)

	H = Sequence([], f.parent().change_ring(QQ))
	for h in filter(None, B*monomials):
		H.append(h)
		I = H.ideal()
		if I.dimension() == -_sage_const_1 :
			H.pop()
		elif I.dimension() == _sage_const_0 :
			roots = []
			for root in I.variety(ring=ZZ):
				root = tuple(R(root[var]) for var in f.variables())
				roots.append(root)
			return roots

	return []

k, s = PolynomialRing(Zmod(e), 'k,s').gens()
f = _sage_const_2 *k*((n+_sage_const_1 )//_sage_const_2  - s) + _sage_const_1 
k,s = small_roots(f, bounds = (floor(pow(n, _sage_const_0p25 )), _sage_const_2 **_sage_const_1024 ), m=_sage_const_3 , d=_sage_const_4 )[_sage_const_0 ]
p,q = var('p q')
p,q = [int(i.right_hand_side()) for i in solve([p*q == n, (p+q) / _sage_const_2  == int(s)], p,q)[_sage_const_0 ]]

d = pow(e, -_sage_const_1 , (p - _sage_const_1 ) * (q - _sage_const_1 ))
print(long_to_bytes(pow(c, d, n)).decode())

